language: haskell
before_install:
  - 'sudo apt-get install cabal-install ghc happy'

install:
  - 'cabal update'
  - 'cabal install --only-dependencies --enable-tests --enable-benchmarks'

script:
  - 'cabal configure'
  - 'cabal build'
  - 'cabal install'
  - 'cabal test'
  - 'cabal sdist'
