language: haskell

  - 'UBUNTU_RELEASE=saucy GHCVER=7.8.1 CABALVER=1.20'
  - 'UBUNTU_RELEASE=trusty GHCVER=7.8.1 CABALVER=1.20'

before_install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ ${UBUNTU_RELEASE} main universe"
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER happy
  - sudo apt-get remove libzmq1
  - wget http://download.zeromq.org/zeromq-4.0.4.tar.gz
  - tar -xf zeromq-4.0.4.tar.gz
  - cd zeromq-4.0.4
  - ./configure
  - make
  - sudo make install
  - sudo su -c "echo '/usr/local/lib' > /etc/ld.so.conf.d/local.conf"
  - sudo ldconfig
  - cd ..
  - 'sudo apt-get install gearman-server'
  - sudo su -c 'echo "ENABLED=\"true\"" >> /etc/default/gearman-server'
  - sudo gearmand -p 4730 -d

install:
  - 'cabal update'
  - 'cabal install --only-dependencies --enable-tests --enable-benchmarks'

script:
  - 'cabal configure'
  - 'cabal build'
  - 'cabal test'
  - 'cabal sdist'
