language: haskell
before_install:
  - 'sudo apt-get install cabal-install ghc happy'
  - 'sudo apt-get install gearman-server'
  - 'sudo service gearman-server start'

install:
  - 'cabal update'

script:
  - 'cabal install --enable-tests --enable-benchmarks'
  - 'cabal test'
  - 'cabal sdist'
