language: haskell
before_install:
  - 'sudo apt-get install cabal-install ghc happy'

install:
  - 'cabal-$CABALVER update'
  - 'cabal-$CABALVER install --only-dependencies --enable-tests --enable-benchmarks'

script:
  - 'cabal-$CABALVER configure'
  - 'cabal-$CABALVER build'
  - 'cabal-$CABALVER sdist'
